FROM ghcr.io/shopware/docker-dev:php8.3-node22-caddy

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-scripts

EXPOSE 8000

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
