FROM ghcr.io/shopware/docker-dev:php8.3-node22-caddy

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-scripts && \
    mkdir -p var/cache var/log && \
    chmod -R 777 var/

EXPOSE 8000

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
